### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by OddDuckMoose** [impshum/Reddit-Daily-Go-Comics-Poster#1]
Traceback (most recent call last):
  File "c:\Users\Dell E7440\Downloads\calvinbot\crackedout\run.py", line 68, in <module>
    main()
  File "c:\Users\Dell E7440\Downloads\calvinbot\crackedout\run.py", line 58, in main
    reddit_poster(target_comic, reddit, target_subreddit, title_prefix)
  File "c:\Users\Dell E7440\Downloads\calvinbot\crackedout\run.py", line 32, in reddit_poster
    comic_url, comic_date = get_random_comic(target_comic)
  File "c:\Users\Dell E7440\Downloads\calvinbot\crackedout\run.py", line 18, in get_random_comic
    comic_url = soup.find('meta', attrs={'property': 'og:image', 'content': True})['content'] + '.jpg'
TypeError: 'NoneType' object is not subscriptable

config settings
[SETTINGS]
schedule_time = 09:45
target_comic = https://www.gocomics.com/random/calvinandhobbes
title_prefix = Random Comic Daily Go!

**Comment by impshum** [comment]
It's capable of grabbing from any comic from gocomics.com. 

`target_comic = calvinandhobbes`

**Comment by OddDuckMoose** [comment]
> 

yep, thanks! I was adding the HTML link for the random calvin comic, and not just 'calvinandhobbes'. DERP. thanks! I SUPER appreciate it
